//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class po
    {
        public int ID { get; set; }
        public Nullable<int> PO_ID { get; set; }
        public int user_id { get; set; }
        public string status { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string Image { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> shopping_date { get; set; }
        public Nullable<int> quantity { get; set; }
    }
}
